// 本地生成单词卡图片
export const generateLocalWordCard = async (userMessage, imageUrl) => {
  try {
    // 从用户消息中提取单词
    const wordMatch = userMessage.match(/我的单词是：(.+?)(?:\n|$)/);
    const word = wordMatch ? wordMatch[1].trim() : 'WORD';
    
    // 创建Canvas元素生成图片
    const createWordCard = (text, backgroundColor, textColor, size = '1024x1024') => {
      const canvas = document.createElement('canvas');
      const [width, height] = size.split('x').map(Number);
      canvas.width = width;
      canvas.height = height;
      
      const ctx = canvas.getContext('2d');
      
      // 背景
      ctx.fillStyle = backgroundColor;
      ctx.fillRect(0, 0, width, height);
      
      // 添加渐变效果
      const gradient = ctx.createLinearGradient(0, 0, width, height);
      gradient.addColorStop(0, backgroundColor);
      gradient.addColorStop(1, textColor);
      ctx.fillStyle = gradient;
      ctx.fillRect(0, 0, width, height);
      
      // 文字
      ctx.fillStyle = textColor;
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      
      // 主单词
      ctx.font = 'bold 120px Arial';
      ctx.fillText(word.toUpperCase(), width / 2, height / 2 - 50);
      
      // 中文释义
      ctx.font = '60px Arial';
      ctx.fillText('单词卡', width / 2, height / 2 + 80);
      
      // 底部信息
      ctx.font = '40px Arial';
      ctx.fillText('Generated by xiaoFu', width / 2, height - 60);
      
      return canvas.toDataURL('image/png');
    };
    
    // 生成正面卡片
    const frontCard = createWordCard(
      word, 
      '#4CAF50', 
      '#FFFFFF'
    );
    
    // 生成反面卡片
    const backCard = createWordCard(
      word, 
      '#2196F3', 
      '#FFFFFF'
    );
    
    return [
      {
        url: frontCard,
        size: '1024x1024'
      },
      {
        url: backCard,
        size: '1024x1024'
      }
    ];
    
  } catch (error) {
    console.error('本地图片生成失败:', error);
    // 返回占位图片
    return [{
      url: 'https://via.placeholder.com/1024x1024/4CAF50/FFFFFF?text=Word+Card+Front',
      size: '1024x1024'
    }, {
      url: 'https://via.placeholder.com/1024x1024/2196F3/FFFFFF?text=Word+Card+Back',
      size: '1024x1024'
    }];
  }
};
